# Introduction {#intro}


  In this thesis, I describe my work developing software in the programming language R to help others more easily achieve their academic and professional goals. The first part of the thesis briefly the programming language R and its rising popularity throughout industry and academia. The middle part consists of three chapters, one for each piece of software developed. I describe the technical background and implementation of each package, an easily shareable unit of code, and provide vignette-like documentation highlighting their main features.
  
  The first package, {discord}, provides user-friendly functions for genetically-informed quasi-experimental designs. It facilitates discordant-kinship regressions by comparing kin, such as siblings, in a manner that accounts for gene-and-environmental confounds when examining causal links in the realm of ‘nature vs. nurture.’
  
  The second package, {shinysurveys}, provides easy-to-use, minimalistic code for creating and deploying surveys in R. It extends the {shiny} package and converts a table of questions into an interactive web-based application. Administering surveys with this package allows users to combine the computational tools of R with the interactivity of web applications. This synergy helps bridge the gap between data collection and data analysis. 
  
  The third package, {ghee}, expands upon the low-level GitHub API package, {gh}. GitHub, an online host for git repositories, is a popular platform for code collaboration. {ghee} provides a curated set of functions to help developers easily perform common tasks on it such as creating repositories and inviting collaborators.
  
  I end each of the main chapters by discussing how to improve upon the software and, in the final section of this thesis, close with an overarching conclusion. The packages described in this thesis have been downloaded over 5500 times. I believe they have really exciting potential, and am excited to see what people do with them.
