# R

For this thesis, I utilized the programming language R. To me, R has three key benefits: cost, extensibility, and a welcoming community. In this chapter, I briefly describe the history of R, touch on its rising popularity, and provide context for the published software discussed in the main thesis chapters.

## What is R?

R is a direct descendant of the statistical environment S, originally developed in 1976 by John Chambers and colleagues at Bell Telephone Laboratories -- associated with AT&T -- for internal use [@rogerd.peng2020]. S was originally implemented in Fortran before being rewritten in C in 1988 [@rogerd.peng2020]. S, like many popular statistical environments such as SPSS or Stata, was only available with a commercial license. In the early 1990s, Ross Ihaka and Robert Gentleman from the University of Auckland developed R, a language combining the strengths of S and Scheme [@ihaka1996].

Technically, R is an interpreted, object-oriented language. R's syntax is similar to S, but its implementation mimics Scheme, and it is primarily implemented in C, C++, and Fortran, which improves its computational efficiency [@ihaka1996; @therfoundation]. At its core, R is "an integrated suite of software facilities for data manipulation, calculation and graphical display" [@therfoundation]. I also believe it is much more. Because of R's extensibility, discussed in the next section, I believe it should be classified as a general programming language. It has, after all, gained widespread popularity in both academia and industry [@carson2016; @ashleevance2009a; @rstudio2018].

## Why is R becoming more popular? {#r-popularity}

One reason for R's rising popularity is its easy extensibility with packages, the fundamental unit of shareable code [@rpkgs]. Packages bundle code, data, documentation, and tests in a common manner which allows all R users to benefit from others' work [@rpkgs]. Packages can be shared internally (e.g. within a research lab) or publicly. The most common way to publicly share your code is through the Comprehensive R Archive Network (CRAN) [@cran]. CRAN provides discoverability, facilitates easy installation, and lends a sense of credibility as each package must pass certain standards [@rpkgs]. At the time of writing,[^why-r-1] CRAN has 17,313 available packages, three of which are discussed in this thesis. Packages exist for everything from implementing hierarchical Bayesian models [@brms] to image manipulation [@magick] and console-based games [@xieaut2020].

[^why-r-1]: March 15, 2021

R is open-source under the Free Software Foundation's [GNU General Public License](https://www.r-project.org/COPYING). Because it is free and has an actively maintained package ecosystem, R is firmly situated as a top choice of programming languages.
