# {shinysurveys} {#shinysurveys}

## Motivation

Surveys are extremely useful tools for gathering information from individuals on a large scale and are used in a variety of domains. Within the medical research field, for example, there are often three types of surveys: epidemiological questionnaires, ones on attitudes towards health services or interventions, and polls to assess knowledge about specific topics [@jones2013]. Neuroscientific research often uses them to correlate behaviors (e.g. political ideology or X) with neuroimaging data (see [@ahn2014] as an example).

The ability to easily collect and analyze survey data is, therefore, extremely important. Many platforms provide user-friendly methods to do this. [Google Forms](https://www.google.com/forms/about/), [SurveyMonkey](https://www.surveymonkey.com/), and [Qualtrics](https://www.qualtrics.com/core-xm/survey-software/) are all popular options. For many cases, they work extremely well. One limitation, though, is often the ease with which they integrate with existing data analysis and/or research pipelines. {shinysurveys} was developed to streamline the data collection and analysis process. It is built off of the programming language R, which is popular throughout academia.

### Why R?

R is an interpreted object-oriented language developed in the early 1990s by Ross Ihaka and Robert Gentleman[@ihaka1996]. R is "an integrated suite of software facilities for data manipulation, calculation and graphical display"[@therfoundation]. It is often thought of as a statistical computing language, though it may be better categorized as an "environment with which statistical techniques are implemented" [@therfoundation]. Recently, it has gained widespread popularity in both academia and industry jobs [@ashleevance2009a; @rstudio2018].

One reason R's rising popularity is its easy extensibility with packages, the fundamental unit of shareable code [@rpkgs]. Packages bundle code, data, documentation, and tests in a common manner which allows all R users to benefit from others' work [@rpkgs]. Packages can be shared internally (e.g. within a research lab) or publicly. The most common way to publicly share your code is through the Comprehensive R Archive Network (CRAN) [@cran]. CRAN provides discoverability, facilitates easy installation, and lends a sense of authenticity (via package submission standards) [@rpkgs]. At the time of writing,[^shinysurveys-1] CRAN has 17,313 available packages (three of which are discussed in this thesis). Packages exist for everything from implementing hierarchical Bayesian models [@brms] to image manipulation [@magick] and console-based games [@xieaut2020].

[^shinysurveys-1]: March 15, 2021

R is available with no fee under the Free Software Foundation's [GNU General Public License](https://www.r-project.org/COPYING). Because of this, and its extensive -- and actively developed -- package ecosystem, R's role in the professional environment is nigh guaranteed.

### Shiny

> Add more about why we developed {shinysurveys}...describe what the programming language R is, what it is used for, the package Shiny, and how our work can be utilized in existing data collection pipelines.

## A survey of {shinysurveys} {#survey-of-shinysurveys}

> `r emo::ji("warning")` vignette coming soon...
