# R

The work discussed in this thesis was primarily done with the programming language R. This choice was brought about because both myself and my advisor(s) were active R users. Why we chose to learn R originally, though, is explained by understanding who, and why, millions of people use R. This brief section describes R and why it's popular.

## What is R?

R is an interpreted, object-oriented language developed in the early 1990s by Ross Ihaka and Robert Gentleman [@ihaka1996]. It is "an integrated suite of software facilities for data manipulation, calculation and graphical display" [@therfoundation]. R is often thought of as a statistical computing language, though it may be better categorized as an "environment with which statistical techniques are implemented" [@therfoundation]. Recently, it has gained widespread popularity in both academia and industry jobs [@carson2016; @ashleevance2009a; @rstudio2018].

## Why is R becoming more popular? 

One reason for R's rising popularity is its easy extensibility with packages, the fundamental unit of shareable code [@rpkgs]. Packages bundle code, data, documentation, and tests in a common manner which allows all R users to benefit from others' work [@rpkgs]. Packages can be shared internally (e.g. within a research lab) or publicly. The most common way to publicly share your code is through the Comprehensive R Archive Network (CRAN) [@cran]. CRAN provides discoverability, facilitates easy installation, and lends a sense of authenticity (each package must pass certain standards) [@rpkgs]. At the time of writing,[^shinysurveys-1] CRAN has 17,313 available packages (three of which are discussed in this thesis). Packages exist for everything from implementing hierarchical Bayesian models [@brms] to image manipulation [@magick] and console-based games [@xieaut2020].

[^shinysurveys-1]: March 15, 2021

R is available with no fee under the Free Software Foundation's [GNU General Public License](https://www.r-project.org/COPYING). Because of this and its extensive, open-source and actively developed, package ecosystem, R is firmly situated as a top choice of programming languages.
