# {shinysurveys} {#shinysurveys}

## Motivation

Surveys are extremely useful tools for gathering information from individuals on a large scale and are used in a variety of domains. Within the medical research field, for example, there are often three types of surveys: epidemiological questionnaires, ones on attitudes towards health services or interventions, and polls to assess knowledge about specific topics [@jones2013]. Neuroscientific research often uses them to correlate behaviors (e.g. political ideology or X) with neuroimaging data (see [@ahn2014] as an example).

The ability to easily collect and analyze survey data is, therefore, extremely important. Many platforms provide user-friendly methods to do this. [Google Forms](https://www.google.com/forms/about/), [SurveyMonkey](https://www.surveymonkey.com/), and [Qualtrics](https://www.qualtrics.com/core-xm/survey-software/) are all popular options. For many cases, they work extremely well. One limitation, though, is often the ease with which they integrate with existing data analysis and/or research pipelines. Because of R's prevalence in academia and research [@rstudio2018a; @carson2016], {shinysurveys} was developed to streamline the data collection and analysis process. To do this, we utilized a package called {shiny}, which makes it easy to build interactive web applications with R [@chang2021].

## What is {shiny}?

> Describe the package Shiny followed by {shinysurveys} and how our work can be utilized in existing data collection pipelines.

## A survey of {shinysurveys} {#survey-of-shinysurveys}

> `r emo::ji("warning")` vignette coming soon...
